---
  - name: Install unzip package
    yum:
      name: unzip
      state: installed
  
  - name: download package
    get_url:
      url: https://github.com/devopsdemoapps/devops-demo-app/archive/1.0.zip
      dest: /tmp/devops-demo-app-1.0.zip
      mode: '0644'
    tags: download_package

  - name: Create a directory if it does not exist
    file:
      path: /opt/app/releases/devops-demo-app-1.0
      state: directory
      mode: '0755'
    tags: create_dir

  - name: unzup archive
    unarchive:
      src: /tmp/devops-demo-app-1.0.zip
      dest: /opt/app/releases/
      #creates: /opt/app/releases/devops-demo-app-1.0
      remote_src: yes
      owner: apache
      group: apache
    tags: unzip_archive

  - name: Create a symbolic link
    file:
      src: /opt/app/releases/devops-demo-app-1.0
      dest: /var/www/html/app
      owner: apache
      group: apache
      state: link
    tags: createa_sym_link
