---
# tasks file for systems---
  - name: create admin user 
    user:
      name: admin
      state: present
      uid: 5001
      group: admin

  - name: remove user dojo if present
    user:
      name: dojo 
      state: absent

  - name: install tree
    yum:
      name: tree
      state: present

  - name: install ntp
    yum:
      name: ntp
      state: present
