---
# tasks file for php
  - name: install php related packages
    yum:
      name: ['php', 'php-mysql']
      state: present
    notify: restart apache services

  - name: Install php additional package on Debian
    package:
      name: "{{ item }}"
      state: installed
    with_items:
      - libapache2-mod-php
    when: ansible_os_family == 'Debian'
    notify: restart apache services
