---
  # Tasks for Fronend role
  - include_vars: "{{ ansible_os_family }}.yml"

  - name: Install unzip package
    yum:
      name: unzip
      state: installed
  
  - name: Create Release path
    file:
      path: /opt/app/releases
      owner: "{{ apache.user }}"
      group: "{{ apache.group }}"
      mode: 0755
      state: directory
    tags: create_release_path
  
  - name: unzup archive
    unarchive:
      src: https://github.com/devopsdemoapps/devops-demo-app/archive/{{ fronend_application.version }}.zip
      dest: /opt/app/releases
      remote_src: yes
      owner: "{{ apache.user }}"
      group: "{{ apache.group }}"
      creates: /opt/app/releases/devops-demo-app-{{ fronend_application.version }}
    tags: unzip_archive

  - name: Create a symbolic link
    file:
      src: /opt/app/releases/devops-demo-app-{{ fronend_application.version }}
      dest: /var/www/html/app
      owner: "{{ apache.user }}"
      group: "{{ apache.group }}"
      state: link
    tags: createa_sym_link

  - name: Update application configuration
    template:
      src: config.ini.j2
      dest: /var/www/html/app/config.ini
      owner: "{{ apache.user }}"
      group: "{{ apache.group }}"
      mode: 0644
