---
  app_server_users:
    admin:
      name: admin
      uid: 5001
      shell: /bin/bash
      home: /home/admin
      group: admin
      state: present
    dojo:
      state: absent

  app_server_packages:
    packages:
      - ntp
      - tree
      - vim
