---
  - name: App servers playbook
    hosts: app
    become: true
    roles:
      - apache
      - php
      - frontend
      # we do not have to add role systems because it was added into apache/meta/main.yml dependensies

